services:
  - type: web
    name: dementia-research-app
    runtime: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEEPL_API_KEY
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /health
